chatbot/urls.py
from django.urls import path
from . import views

app_name = "chatbot"

urlpatterns = [
    path("", views.chatbot, name="chat"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("post/", include("post.urls")),
    path("user/", include("user.urls")),
    path("chatbot/", include("chatbot.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BTTZ{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>

<body>
    {% include 'navbar.html' %}
    <div id="cursor-trail"></div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/cursor.js' %}"></script>
</body>

</html>

templates/footer.html
<footer>
    <p>&copy; 2025 BTTZ. All rights reserved.</p>
</footer>

templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'post_list_html' %}">Home</a></li>
        <li><a href="{% url 'chatbot:chat' %}">Chatbot</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'user_profile' %}">Profile</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
    </ul>
</nav>